# Generated by Django 4.2 on 2025-06-10 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_product_main_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Pending, Processing, Shipped, Delivered, Cancelled', max_length=50, unique=True)),
                ('description', models.CharField(blank=True, help_text='Optional description of the status', max_length=255, null=True)),
                ('is_default', models.BooleanField(default=False, help_text='Is this the default status for new orders?')),
                ('is_final', models.BooleanField(default=False, help_text='Does this status mean the order is closed (e.g., Delivered, Cancelled)?')),
            ],
            options={
                'verbose_name_plural': 'Order Statuses',
            },
        ),
        migrations.RemoveField(
            model_name='order',
            name='complete',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.orderstatus'),
        ),
    ]
