# Generated by Django 4.2 on 2025-06-23 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_orderstatus_remove_order_complete_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='kode_pos',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='kota',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
