# Generated by Django 4.2 on 2025-06-23 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_shippingaddress_kode_pos_alter_shippingaddress_kota'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
