# Generated by Django 4.2 on 2025-06-24 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_shippingaddress_latitude_shippingaddress_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='longitude',
        ),
    ]
