# Generated by Django 4.2 on 2025-06-09 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_sellerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
